version: '3.1'
services:
  api:
    image: "rajat0206/otpapp:1.0"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/rapipay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=321in#@!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: mysql
    volumes:
      - db-data:/rapipay
    ports:
      - "8001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=321in#@!
      - MYSQL_DATABASE=rapipay
      - MYSQL_PASSWORD=321in#@!
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-data: